import { Kitchen, MenuItem, Order, User, Review } from "@/types";

export const mockUsers: User[] = [
  {
    id: "user-1",
    email: "maria@example.com",
    name: "Maria Garcia",
    role: "cook",
    phone: "(555) 123-4567",
    address: {
      street: "742 Maple Street",
      city: "Austin",
      state: "TX",
      zip: "78701",
      lat: 30.2672,
      lng: -97.7431,
    },
    createdAt: "2025-06-15T10:00:00Z",
  },
  {
    id: "user-2",
    email: "james@example.com",
    name: "James Chen",
    role: "cook",
    phone: "(555) 234-5678",
    address: {
      street: "1234 Oak Avenue",
      city: "Austin",
      state: "TX",
      zip: "78702",
      lat: 30.2622,
      lng: -97.7261,
    },
    createdAt: "2025-07-01T10:00:00Z",
  },
  {
    id: "user-3",
    email: "priya@example.com",
    name: "Priya Patel",
    role: "cook",
    phone: "(555) 345-6789",
    address: {
      street: "567 Elm Drive",
      city: "Austin",
      state: "TX",
      zip: "78703",
      lat: 30.2849,
      lng: -97.7614,
    },
    createdAt: "2025-07-10T10:00:00Z",
  },
  {
    id: "customer-1",
    email: "alex@example.com",
    name: "Alex Johnson",
    role: "customer",
    phone: "(555) 456-7890",
    address: {
      street: "890 Pine Road",
      city: "Austin",
      state: "TX",
      zip: "78704",
      lat: 30.2501,
      lng: -97.7539,
    },
    createdAt: "2025-08-01T10:00:00Z",
  },
];

export const mockKitchens: Kitchen[] = [
  {
    id: "kitchen-1",
    cookId: "user-1",
    name: "Maria's Mexican Kitchen",
    description:
      "Authentic Mexican home cooking passed down through three generations. Every dish is made with love using fresh, locally-sourced ingredients and traditional family recipes from Oaxaca.",
    cuisineTypes: ["Mexican", "Latin American"],
    address: {
      street: "742 Maple Street",
      city: "Austin",
      state: "TX",
      zip: "78701",
      lat: 30.2672,
      lng: -97.7431,
    },
    coverImage: "",
    profileImage: "",
    rating: 4.8,
    reviewCount: 124,
    isOpen: true,
    operatingHours: [
      { day: "Monday", open: "11:00", close: "20:00", isClosed: false },
      { day: "Tuesday", open: "11:00", close: "20:00", isClosed: false },
      { day: "Wednesday", open: "11:00", close: "20:00", isClosed: false },
      { day: "Thursday", open: "11:00", close: "21:00", isClosed: false },
      { day: "Friday", open: "11:00", close: "22:00", isClosed: false },
      { day: "Saturday", open: "10:00", close: "22:00", isClosed: false },
      { day: "Sunday", open: "10:00", close: "18:00", isClosed: false },
    ],
    healthPermitNumber: "HP-2025-001234",
    maxOrdersPerHour: 8,
    preparationTimeMinutes: 30,
    deliveryRadiusMiles: 5,
    minimumOrderAmount: 15,
    createdAt: "2025-06-15T10:00:00Z",
  },
  {
    id: "kitchen-2",
    cookId: "user-2",
    name: "Chen's Dumpling House",
    description:
      "Handmade dumplings and authentic Sichuan dishes prepared fresh daily. Chef James brings 20 years of family cooking tradition from Chengdu to your doorstep.",
    cuisineTypes: ["Chinese", "Sichuan", "Dumplings"],
    address: {
      street: "1234 Oak Avenue",
      city: "Austin",
      state: "TX",
      zip: "78702",
      lat: 30.2622,
      lng: -97.7261,
    },
    coverImage: "",
    profileImage: "",
    rating: 4.9,
    reviewCount: 89,
    isOpen: true,
    operatingHours: [
      { day: "Monday", open: "11:30", close: "21:00", isClosed: false },
      { day: "Tuesday", open: "11:30", close: "21:00", isClosed: false },
      { day: "Wednesday", open: "11:30", close: "21:00", isClosed: false },
      { day: "Thursday", open: "11:30", close: "21:00", isClosed: false },
      { day: "Friday", open: "11:30", close: "22:00", isClosed: false },
      { day: "Saturday", open: "11:00", close: "22:00", isClosed: false },
      { day: "Sunday", open: "12:00", close: "20:00", isClosed: false },
    ],
    healthPermitNumber: "HP-2025-001567",
    maxOrdersPerHour: 10,
    preparationTimeMinutes: 25,
    deliveryRadiusMiles: 4,
    minimumOrderAmount: 20,
    createdAt: "2025-07-01T10:00:00Z",
  },
  {
    id: "kitchen-3",
    cookId: "user-3",
    name: "Priya's Spice Garden",
    description:
      "Experience the rich flavors of India with dishes crafted using freshly ground spices and time-honored techniques. From creamy butter chicken to crispy dosas, every meal is a celebration.",
    cuisineTypes: ["Indian", "South Indian", "Vegetarian"],
    address: {
      street: "567 Elm Drive",
      city: "Austin",
      state: "TX",
      zip: "78703",
      lat: 30.2849,
      lng: -97.7614,
    },
    coverImage: "",
    profileImage: "",
    rating: 4.7,
    reviewCount: 67,
    isOpen: false,
    operatingHours: [
      { day: "Monday", open: "11:00", close: "14:00", isClosed: false },
      { day: "Tuesday", open: "11:00", close: "14:00", isClosed: false },
      { day: "Wednesday", open: "11:00", close: "14:00", isClosed: false },
      { day: "Thursday", open: "11:00", close: "21:00", isClosed: false },
      { day: "Friday", open: "11:00", close: "21:00", isClosed: false },
      { day: "Saturday", open: "11:00", close: "21:00", isClosed: false },
      { day: "Sunday", open: "00:00", close: "00:00", isClosed: true },
    ],
    healthPermitNumber: "HP-2025-002345",
    maxOrdersPerHour: 6,
    preparationTimeMinutes: 35,
    deliveryRadiusMiles: 6,
    minimumOrderAmount: 18,
    createdAt: "2025-07-10T10:00:00Z",
  },
];

export const mockMenuItems: MenuItem[] = [
  // Maria's Mexican Kitchen
  {
    id: "menu-1",
    kitchenId: "kitchen-1",
    name: "Enchiladas Oaxaqueñas",
    description:
      "Three corn tortillas filled with shredded chicken, topped with rich mole negro sauce, crema, and queso fresco.",
    price: 14.99,
    image: "",
    category: "Entrees",
    allergens: ["Dairy", "Gluten", "Nuts"],
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 25,
  },
  {
    id: "menu-2",
    kitchenId: "kitchen-1",
    name: "Street-Style Tacos (3)",
    description:
      "Three soft corn tortillas with your choice of carne asada, al pastor, or carnitas. Topped with cilantro, onion, and salsa verde.",
    price: 11.99,
    image: "",
    category: "Entrees",
    allergens: ["Gluten"],
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 15,
  },
  {
    id: "menu-3",
    kitchenId: "kitchen-1",
    name: "Guacamole & Chips",
    description:
      "Fresh-made guacamole with avocado, lime, cilantro, jalapeño, and tomato. Served with crispy homemade tortilla chips.",
    price: 8.99,
    image: "",
    category: "Appetizers",
    allergens: [],
    isAvailable: true,
    isPopular: false,
    preparationTimeMinutes: 10,
  },
  {
    id: "menu-4",
    kitchenId: "kitchen-1",
    name: "Tamales (4 pack)",
    description:
      "Handmade tamales filled with pork in red chile sauce, wrapped in corn husks and steamed to perfection.",
    price: 16.99,
    image: "",
    category: "Entrees",
    allergens: ["Gluten"],
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 20,
  },
  {
    id: "menu-5",
    kitchenId: "kitchen-1",
    name: "Horchata",
    description: "Traditional Mexican rice drink with cinnamon and vanilla. Ice cold and refreshing.",
    price: 4.99,
    image: "",
    category: "Drinks",
    allergens: ["Dairy"],
    isAvailable: true,
    isPopular: false,
    preparationTimeMinutes: 5,
  },
  {
    id: "menu-6",
    kitchenId: "kitchen-1",
    name: "Tres Leches Cake",
    description:
      "Moist sponge cake soaked in three milks, topped with whipped cream and a sprinkle of cinnamon.",
    price: 7.99,
    image: "",
    category: "Desserts",
    allergens: ["Dairy", "Eggs", "Gluten"],
    isAvailable: true,
    isPopular: false,
    preparationTimeMinutes: 5,
  },

  // Chen's Dumpling House
  {
    id: "menu-7",
    kitchenId: "kitchen-2",
    name: "Pork & Chive Dumplings (12)",
    description:
      "Hand-folded dumplings with seasoned pork and fresh chives. Steamed or pan-fried to order.",
    price: 13.99,
    image: "",
    category: "Dumplings",
    allergens: ["Gluten", "Soy"],
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 20,
  },
  {
    id: "menu-8",
    kitchenId: "kitchen-2",
    name: "Xiao Long Bao (8)",
    description: "Delicate soup dumplings filled with pork and a rich, savory broth. Handle with care!",
    price: 15.99,
    image: "",
    category: "Dumplings",
    allergens: ["Gluten", "Soy"],
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 25,
  },
  {
    id: "menu-9",
    kitchenId: "kitchen-2",
    name: "Mapo Tofu",
    description:
      "Silken tofu in a fiery Sichuan peppercorn and chili bean sauce with minced pork. Served with steamed rice.",
    price: 12.99,
    image: "",
    category: "Entrees",
    allergens: ["Soy", "Gluten"],
    isAvailable: true,
    isPopular: false,
    preparationTimeMinutes: 15,
  },
  {
    id: "menu-10",
    kitchenId: "kitchen-2",
    name: "Dan Dan Noodles",
    description:
      "Spicy Sichuan noodles with minced pork, preserved vegetables, chili oil, and crushed peanuts.",
    price: 11.99,
    image: "",
    category: "Noodles",
    allergens: ["Gluten", "Soy", "Peanuts"],
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 15,
  },
  {
    id: "menu-11",
    kitchenId: "kitchen-2",
    name: "Vegetable Spring Rolls (4)",
    description: "Crispy fried spring rolls with cabbage, carrots, mushrooms, and glass noodles.",
    price: 7.99,
    image: "",
    category: "Appetizers",
    allergens: ["Gluten", "Soy"],
    isAvailable: true,
    isPopular: false,
    preparationTimeMinutes: 10,
  },

  // Priya's Spice Garden
  {
    id: "menu-12",
    kitchenId: "kitchen-3",
    name: "Butter Chicken",
    description:
      "Tender chicken pieces in a velvety tomato-cream sauce with aromatic spices. Served with basmati rice and naan.",
    price: 15.99,
    image: "",
    category: "Entrees",
    allergens: ["Dairy", "Gluten"],
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 30,
  },
  {
    id: "menu-13",
    kitchenId: "kitchen-3",
    name: "Masala Dosa",
    description:
      "Crispy rice and lentil crepe filled with spiced potato filling. Served with coconut chutney and sambar.",
    price: 12.99,
    image: "",
    category: "South Indian",
    allergens: [],
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 20,
  },
  {
    id: "menu-14",
    kitchenId: "kitchen-3",
    name: "Palak Paneer",
    description: "Fresh cottage cheese cubes in a creamy spinach gravy. Served with basmati rice.",
    price: 13.99,
    image: "",
    category: "Vegetarian",
    allergens: ["Dairy"],
    isAvailable: true,
    isPopular: false,
    preparationTimeMinutes: 25,
  },
  {
    id: "menu-15",
    kitchenId: "kitchen-3",
    name: "Samosa (3)",
    description:
      "Crispy pastry triangles filled with spiced potatoes and peas. Served with mint and tamarind chutneys.",
    price: 6.99,
    image: "",
    category: "Appetizers",
    allergens: ["Gluten"],
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 10,
  },
  {
    id: "menu-16",
    kitchenId: "kitchen-3",
    name: "Mango Lassi",
    description: "Refreshing yogurt smoothie blended with ripe Alphonso mangoes and a hint of cardamom.",
    price: 5.99,
    image: "",
    category: "Drinks",
    allergens: ["Dairy"],
    isAvailable: true,
    isPopular: false,
    preparationTimeMinutes: 5,
  },
  {
    id: "menu-17",
    kitchenId: "kitchen-3",
    name: "Garlic Naan (2)",
    description: "Soft, pillowy flatbread brushed with garlic butter, baked in a tandoor-style oven.",
    price: 4.99,
    image: "",
    category: "Breads",
    allergens: ["Dairy", "Gluten"],
    isAvailable: true,
    isPopular: false,
    preparationTimeMinutes: 10,
  },
];

export const mockOrders: Order[] = [
  {
    id: "order-1",
    customerId: "customer-1",
    customerName: "Alex Johnson",
    kitchenId: "kitchen-1",
    kitchenName: "Maria's Mexican Kitchen",
    items: [
      { menuItemId: "menu-1", name: "Enchiladas Oaxaqueñas", price: 14.99, quantity: 1 },
      { menuItemId: "menu-2", name: "Street-Style Tacos (3)", price: 11.99, quantity: 2 },
      { menuItemId: "menu-5", name: "Horchata", price: 4.99, quantity: 2 },
    ],
    subtotal: 48.95,
    deliveryFee: 4.99,
    serviceFee: 3.49,
    tip: 8.0,
    total: 65.43,
    status: "preparing",
    deliveryAddress: {
      street: "890 Pine Road",
      city: "Austin",
      state: "TX",
      zip: "78704",
      lat: 30.2501,
      lng: -97.7539,
    },
    deliveryProvider: "DoorDash",
    estimatedDeliveryTime: "2026-02-15T13:15:00Z",
    createdAt: "2026-02-15T12:30:00Z",
    updatedAt: "2026-02-15T12:35:00Z",
  },
  {
    id: "order-2",
    customerId: "customer-1",
    customerName: "Alex Johnson",
    kitchenId: "kitchen-2",
    kitchenName: "Chen's Dumpling House",
    items: [
      { menuItemId: "menu-8", name: "Xiao Long Bao (8)", price: 15.99, quantity: 1 },
      { menuItemId: "menu-10", name: "Dan Dan Noodles", price: 11.99, quantity: 1 },
    ],
    subtotal: 27.98,
    deliveryFee: 3.99,
    serviceFee: 2.49,
    tip: 5.0,
    total: 39.46,
    status: "delivered",
    deliveryAddress: {
      street: "890 Pine Road",
      city: "Austin",
      state: "TX",
      zip: "78704",
      lat: 30.2501,
      lng: -97.7539,
    },
    deliveryProvider: "DoorDash",
    deliveryTrackingUrl: "https://doordash.com/track/abc123",
    createdAt: "2026-02-14T18:00:00Z",
    updatedAt: "2026-02-14T19:05:00Z",
  },
];

export const mockReviews: Review[] = [
  {
    id: "review-1",
    orderId: "order-2",
    customerId: "customer-1",
    customerName: "Alex J.",
    kitchenId: "kitchen-2",
    rating: 5,
    comment:
      "The soup dumplings were incredible! So delicate and flavorful. The dan dan noodles had the perfect kick. Will definitely order again!",
    createdAt: "2026-02-14T19:30:00Z",
  },
  {
    id: "review-2",
    orderId: "order-100",
    customerId: "customer-50",
    customerName: "Sarah M.",
    kitchenId: "kitchen-1",
    rating: 5,
    comment:
      "Best enchiladas I've ever had outside of Mexico. Maria's mole sauce is out of this world. The tamales are perfection too!",
    createdAt: "2026-02-10T20:00:00Z",
  },
  {
    id: "review-3",
    orderId: "order-101",
    customerId: "customer-51",
    customerName: "Mike R.",
    kitchenId: "kitchen-1",
    rating: 4,
    comment: "Great tacos and really fresh guacamole. Delivery was fast. Will be back for more.",
    createdAt: "2026-02-08T19:00:00Z",
  },
  {
    id: "review-4",
    orderId: "order-102",
    customerId: "customer-52",
    customerName: "Lisa T.",
    kitchenId: "kitchen-3",
    rating: 5,
    comment:
      "Priya's butter chicken is the most authentic I've found in Austin. The naan was perfectly fluffy and the samosas were crispy. A real gem!",
    createdAt: "2026-02-12T20:30:00Z",
  },
];
